import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Coach from "../components/Coach";
import { CoachProfile } from "../types/coach";
import Logo from "../components/Logo";

// REVIEW IMPORT FORM JSON COACH
const coachArray = [
    {
        name: "Gimena",
        img: "/img/coaches/gimena.jpg",
        description: "FS Coach from Spiced Berlin",
    },
    {
        name: "Jan",
        img: "/img/coaches/jan.png",
        description: "FS Coach from Spiced Berlin",
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Xmas Coding Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {/* className={styles.header} */}
                <header className="header">
                    <Logo />
                    {/* className={styles.nav} */}
                    <nav className="nav">
                        {/* className={styles.navOption} */}
                        <Link
                            href={"#welcome-section"}
                            scroll={false}
                            className="navOption"
                        >
                            Welcome
                        </Link>
                        <Link
                            href={"#coaches-section"}
                            scroll={false}
                            className="navOption"
                        >
                            Coaches
                        </Link>
                        <Link
                            href={"#links-section"}
                            scroll={false}
                            className="navOption"
                        >
                            Material
                        </Link>
                        <Link
                            href={"#partners-section"}
                            scroll={false}
                            className="navOption"
                        >
                            Partners
                        </Link>
                    </nav>
                </header>
                <section
                    id="welcome-section"
                    className={`${styles.section} ${styles.welcomeSection}`}
                >
                    <h1 className={styles.title}>Women&apos;s Xmas Coding</h1>
                    {/* <Image
                        src="/img/home/xmas-coding.png"
                        alt="Vercel Logo"
                        width={500}
                        height={500}
                        objectFit="cover"
                    /> */}
                </section>

                <section
                    id="coaches-section"
                    className={`${styles.section} ${styles.coachesSection}`}
                >
                    {/* Here will be the introduction of the trainees. */}
                    <h1 className={styles.titleSection}>Your Xmas Coaches</h1>
                    <div className={styles.coachesProfile}>
                        {coachArray &&
                            coachArray.map((each: CoachProfile, key) => {
                                return <Coach {...each} key={key} />;
                            })}
                    </div>
                </section>

                <section
                    id="links-section"
                    className={`${styles.section} ${styles.linksSection}`}
                >
                    <h1 className={styles.titleSection}>Material</h1>

                    <div className={`${styles.grid} `}>
                        <Link href="/material" className={styles.card}>
                            <h2>Material &rarr;</h2>
                            <p>Find the material form the event here.</p>
                        </Link>

                        <Link
                            href="https://nextjs.org/learn"
                            target="_blank"
                            className={styles.card}
                        >
                            <h2>Xmas Card &rarr;</h2>
                            <p>
                                Here you will find the initial code to do your
                                own Card!
                            </p>
                        </Link>
                        <Link
                            href="https://xmas-coding-2022.vercel.app "
                            target="_blank"
                            className={styles.card}
                        >
                            <h2>Xmas Card Board &rarr;</h2>
                            <p>Upload your card and see all the other cards</p>
                        </Link>

                        <Link
                            href="https://www.spiced-academy.com/en"
                            target="_blank"
                            className={styles.card}
                        >
                            <h2>SPICED Academy &rarr;</h2>
                            <p>Take a look in our web side and our programs</p>
                        </Link>
                    </div>
                </section>
                <section
                    id="partners-section"
                    className={`${styles.section} ${styles.partnerSection}`}
                >
                    <h1 className={styles.title}>Our Partners</h1>
                    {/* <Image
                        src="/img/home/xmas-coding.png"
                        alt="Vercel Logo"
                        width={500}
                        height={500}
                        objectFit="cover"
                    /> */}
                </section>
            </main>
        </>
    );
}
