import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Coach from "../components/Coach";
import { CoachProfile } from "../types/coach";
import Logo from "../components/Logo";

// REVIEW IMPORT FORM JSON COACH
const coachArray = [
    {
        name: "Gimena",
        img: "/img/coaches/gimena.jpg",
        description: "FS Coach from Spiced Berlin",
    },
    {
        name: "Jan",
        img: "/img/coaches/jan.png",
        description: "FS Coach from Spiced Berlin",
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Xmas Coding Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <header className={styles.header}>
                    <Logo />
                    <nav className={styles.nav}>
                        <Link href={"#welcome-section"} scroll={false}>
                            Welcome
                        </Link>
                        <Link href={"#coaches-section"} scroll={false}>
                            Coaches
                        </Link>
                        <Link href={"#material-section"} scroll={false}>
                            Material
                        </Link>
                        <Link href={"#partners-section"} scroll={false}>
                            Partners
                        </Link>
                    </nav>
                </header>
                <section
                    id="welcome-section"
                    className={`${styles.section} ${styles.welcomeSection}`}
                >
                    <h1 className={styles.title}>Women&apos;s Xmas Coding</h1>
                    {/* <Image
                        src="/img/home/xmas-coding.png"
                        alt="Vercel Logo"
                        width={500}
                        height={500}
                        objectFit="cover"
                    /> */}
                </section>

                <section
                    id="coaches-section"
                    className={`${styles.section} ${styles.coachesSection}`}
                >
                    {/* Here will be the introduction of the trainees. */}
                    <h1>Your Xmas Coaches</h1>
                    <div className={styles.coachesProfile}>
                        {coachArray &&
                            coachArray.map((each: CoachProfile, key) => {
                                return <Coach {...each} key={key} />;
                            })}
                    </div>
                </section>

                <section
                    id="material-section"
                    className={`${styles.section} ${styles.materialSection}`}
                >
                    <div className={`${styles.grid} `}>
                        <a href="/Material" className={styles.card}>
                            <h2>Material &rarr;</h2>
                            <p>Find the material form the event here.</p>
                        </a>

                        <a
                            href="https://nextjs.org/learn"
                            className={styles.card}
                        >
                            <h2>Xmas Card &rarr;</h2>
                            <p>
                                Here you will find the initial code to do your
                                own Card!
                            </p>
                        </a>
                        <a href="/Material" className={styles.card}>
                            <h2>Xmas Card Board &rarr;</h2>
                            <p>Upload your card and see all the other cards</p>
                        </a>
                        <a href="/Material" className={styles.card}>
                            <h2>More &rarr;</h2>
                            <p>Upload your card and see all the other cards</p>
                        </a>
                    </div>
                </section>
                <section
                    id="partner-section"
                    className={`${styles.section} ${styles.partnerSection}`}
                >
                    <h1 className={styles.title}>Our Partners</h1>
                    {/* <Image
                        src="/img/home/xmas-coding.png"
                        alt="Vercel Logo"
                        width={500}
                        height={500}
                        objectFit="cover"
                    /> */}
                </section>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </>
    );
}
